services:
  db:
    container_name: db
    image: mysql:9.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./compose/mysql/init:/docker-entrypoint-initdb.d
      - ./compose/mysql/my.conf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_db
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_pass
    healthcheck:
      test: mysqladmin ping -ulocal_user -plocal_pass
      timeout: 10s
      interval: 5s
      retries: 10
