---
openapi: 3.1.0
components:
  schemas:
    BookOrder:
      type: string
      enum:
      - +price
      - -price
    BookStatus:
      type: string
      enum:
      - UNPUBLISHED
      - PUBLISHED
      - OUT_OF_PRINT
    Hit:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples:
          - 1
        isbn:
          type: string
          examples:
          - "9784621303252"
        title:
          type: string
          examples:
          - Effective Java 第3版
        price:
          type: integer
          format: int32
          examples:
          - 4400
        status:
          type: string
          examples:
          - PUBLISHED
          $ref: "#/components/schemas/BookStatus"
    Pagination:
      type: object
      properties:
        offset:
          type: integer
          format: int32
        limit:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
    findBooksResponse:
      type: object
      properties:
        pagination:
          $ref: "#/components/schemas/Pagination"
        hits:
          type: array
          items:
            $ref: "#/components/schemas/Hit"
info:
  title: API仕様書
  version: 1.0.0
tags:
- name: book
servers:
- url: http://localhost:8080
  description: ローカル環境
paths:
  /api/v1/books:
    get:
      summary: booksを検索する
      operationId: findBooks
      tags:
      - book
      parameters:
      - name: isbn
        in: query
        schema:
          type: string
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
          maximum: 100
          minimum: 1
          default: "100"
      - name: offset
        in: query
        schema:
          type: integer
          format: int32
          minimum: 0
          default: "0"
      - name: order
        in: query
        schema:
          allOf:
          - $ref: "#/components/schemas/BookOrder"
          - default: -price
      - name: priceFrom
        in: query
        schema:
          type: integer
          format: int32
          minimum: 0
      - name: priceTo
        in: query
        schema:
          type: integer
          format: int32
          minimum: 0
      - name: title
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/findBooksResponse"
